In [ ]:
# !pip install sidpy

In [33]:
import numpy as np
from sidpy.sid.dataset import Dataset
from sidpy.sid.dimension import Dimension

In [34]:
data = np.random.rand(4, 5, 6, 7)  # e.g., X=4, Y=5, Voltage=6, Time=7 

In [35]:
data.shape

(4, 5, 6, 7)

In [36]:
data[0, 0, 0, :]

array([0.58149981, 0.61111301, 0.28736465, 0.98533436, 0.05399884,
       0.63023349, 0.30315287])

In [37]:
def create_sidpy_dataset_dynamic(data):
    dset = Dataset.from_array(data, title="Dynamic Dataset")

    for i in range(data.ndim):
        print(f"\n--- Axis {i} ---")
        name = input("Axis name: ")
        quantity = input("Quantity: ")
        units = input("Units: ")
        values = np.arange(data.shape[i])  # default
        
        dim = Dimension(values, name=name, quantity=quantity, units=units)
        dset.set_dimension(i, dim)
    
    return dset

In [38]:
dset = create_sidpy_dataset_dynamic(data)


--- Axis 0 ---


Axis name:  X
Quantity:  distance
Units:  mm



--- Axis 1 ---


Axis name:  Y
Quantity:  distance
Units:  mm



--- Axis 2 ---


Axis name:  Voltage
Quantity:  voltage
Units:  V



--- Axis 3 ---


Axis name:  Time
Quantity:  time
Units:  s


In [39]:
dset

sidpy.Dataset of type UNKNOWN with:
 dask.array<array, shape=(4, 5, 6, 7), dtype=float64, chunksize=(4, 5, 6, 7), chunktype=numpy.ndarray>
 data contains: generic (generic)
 and Dimensions: 
X:  distance (mm) of size (4,)
Y:  distance (mm) of size (5,)
Voltage:  voltage (V) of size (6,)
Time:  time (s) of size (7,)

In [40]:
dset.Time.values

array([0., 1., 2., 3., 4., 5., 6.])

In [41]:
dset.compute()[0, 0, 0, :]

array([0.58149981, 0.61111301, 0.28736465, 0.98533436, 0.05399884,
       0.63023349, 0.30315287])